version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - /mnt/data/jenkins_data/jenkins_home:/var/jenkins_home
      - /mnt/data/jenkins_data/log:/var/log
    ports:
      - 8081:8081
      - 50000:50000